version: '3'
services:
  server:
    build:
      context: ./
      dockerfile: Server.Ubuntu
    container_name: server
    ports:
      - 5000:5000
    volumes:
      - .:/usr/src/app
    networks:
      - client-server
  cliente:
    stdin_open: true
    tty: true
    build:
      context: ./
      dockerfile: Cliente.Ubuntu
    container_name: cliente
    ports:
     - 5001:5000
    depends_on:
      - server
    volumes:
      - .:/usr/src/app
    networks:
      - client-server
networks:
  client-server:
    driver: bridge