version: '3'
services:
  server:
    build:
      context: ./
      dockerfile: server.docker
    container_name: server
    ports:
      - 5000:5000
    volumes:
      - .:/app
  client:
    stdin_open: true
    tty: true
    build:
      context: ./
      dockerfile: client.docker
    container_name: client
    ports:
      - 5001:5001
    volumes:
      - .:/app
    depends_on:
      - server