version: '3'

services: 
  server:
    build:
      context: ./
      dockerfile: Dockerfile.server
    container_name: server
    ports:
      - 5000:5000
    volumes:
      - .:/usr/src/app
  cliente:
    build:
      context: ./
      dockerfile: Dockerfile.cliente
    container_name: cliente
    ports:
     - 5001:5000
    volumes:
      - .:/usr/src/app
    depends_on:
      - server