version: '3'

services: 
  server:
    build: ./server 
    volumes:
      - ./server:/usr/src/app
    ports:
      - 10000:5000
  node1:
    build: ./node1
    volumes:
      - ./node1:/usr/src/app
    ports:
      - 5000:10000
    depends_on:
      - server