version: '3'
services:
  headnode:
    stdin_open: true
    tty: true
    build:
      context: ./
      dockerfile: Dockerfile.headnode
    container_name: headnode
    ports:
      - 10000:10000
      - 5000:5000
      - 6000:6000
    volumes:
      - .:/usr/src/app
    networks:
      mcast-network:
       ipv4_address: 172.18.18.2
      client-server:
       ipv4_address: 172.24.24.2
  node1:
    stdin_open: true
    tty: true
    build:
      context: ./
      dockerfile: Dockerfile.node
    container_name: node1
    ports:
     - 10001:10000
     - 6001:6000
    volumes:
      - .:/usr/src/app
    networks:
      mcast-network:
       ipv4_address: 172.18.18.3
  node2:
    stdin_open: true
    tty: true
    build:
      context: ./
      dockerfile: Dockerfile.node
    container_name: node2
    ports:
     - 10002:10000
     - 6002:6000
    volumes:
      - .:/usr/src/app
    networks:
      mcast-network:
       ipv4_address: 172.18.18.4
  node3:
    stdin_open: true
    tty: true
    build:
      context: ./
      dockerfile: Dockerfile.node
    container_name: node3
    ports:
     - 10003:10000
     - 6003:6000
    volumes:
      - .:/usr/src/app
    networks:
      mcast-network:
       ipv4_address: 172.18.18.5
  cliente:
    stdin_open: true
    tty: true
    build:
      context: ./
      dockerfile: Dockerfile.cliente
    container_name: cliente
    ports:
     - 5001:5000
    volumes:
      - .:/usr/src/app
    depends_on:
      - headnode
    networks:
      client-server:
       ipv4_address: 172.24.24.3
  
networks:
  mcast-network:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.18.18.0/24
  client-server:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.24.24.0/24
