version: '3'
services:
  headnode:
    stdin_open: true
    tty: true
    build:
      context: ./
      dockerfile: Dockerfile.headnode
    container_name: headnode
    ports:
      - 10000:10000
      - 5000:5000
    volumes:
      - .:/usr/src/app
    networks:
      - mcast-network
  node1:
    stdin_open: true
    tty: true
    build:
      context: ./
      dockerfile: Dockerfile.node
    container_name: node1
    ports:
     - 10001:10000
    volumes:
      - .:/usr/src/app
    networks:
      - mcast-network
  node2:
    stdin_open: true
    tty: true
    build:
      context: ./
      dockerfile: Dockerfile.node
    container_name: node2
    ports:
     - 10002:10000
    volumes:
      - .:/usr/src/app
    networks:
      - mcast-network
  node3:
    stdin_open: true
    tty: true
    build:
      context: ./
      dockerfile: Dockerfile.node
    container_name: node3
    ports:
     - 10003:10000
    volumes:
      - .:/usr/src/app
    networks:
      - mcast-network
  
networks:
  mcast-network:
    driver: bridge