version: '3'
services:
  headnode:
    stdin_open: true
    tty: true
    build:
      context: ./
      dockerfile: Dockerfile.headnode
    container_name: headnode
    ports:
      - 10000:10000
      - 5000:5000
      - 6000:6000
    volumes:
      - .:/usr/src/app
    networks:
      - mcast-network
      - client-server
  node1:
    stdin_open: true
    tty: true
    build:
      context: ./
      dockerfile: Dockerfile.node
    container_name: node1
    ports:
     - 10001:10000
     - 6001:6000
    volumes:
      - .:/usr/src/app
    networks:
      - mcast-network
  node2:
    stdin_open: true
    tty: true
    build:
      context: ./
      dockerfile: Dockerfile.node
    container_name: node2
    ports:
     - 10002:10000
     - 6002:6000
    volumes:
      - .:/usr/src/app
    networks:
      - mcast-network
  node3:
    stdin_open: true
    tty: true
    build:
      context: ./
      dockerfile: Dockerfile.node
    container_name: node3
    ports:
     - 10003:10000
     - 6003:6000
    volumes:
      - .:/usr/src/app
    networks:
      - mcast-network
  cliente:
    stdin_open: true
    tty: true
    build:
      context: ./
      dockerfile: Dockerfile.cliente
    container_name: cliente
    ports:
     - 5001:5000
    
    depends_on:
      - headnode
    networks:
      - client-server
  
networks:
  mcast-network:
    driver: bridge
  client-server:
    driver: bridge